/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperRouteImport } from './routes/_authenticated/super'
import { Route as AuthenticatedDowntimeRouteImport } from './routes/_authenticated/downtime'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicRecordProductionRouteImport } from './routes/api/public/record-production'
import { Route as ApiPublicAdminRelayRouteImport } from './routes/api/public/admin-relay'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperRoute = AuthenticatedSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDowntimeRoute = AuthenticatedDowntimeRouteImport.update({
  id: '/downtime',
  path: '/downtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRecordProductionRoute =
  ApiPublicRecordProductionRouteImport.update({
    id: '/api/public/record-production',
    path: '/api/public/record-production',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminRelayRoute = ApiPublicAdminRelayRouteImport.update({
  id: '/api/public/admin-relay',
  path: '/api/public/admin-relay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv': typeof TvRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/super': typeof AuthenticatedSuperRoute
  '/api/public/admin-relay': typeof ApiPublicAdminRelayRoute
  '/api/public/record-production': typeof ApiPublicRecordProductionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv': typeof TvRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/super': typeof AuthenticatedSuperRoute
  '/api/public/admin-relay': typeof ApiPublicAdminRelayRoute
  '/api/public/record-production': typeof ApiPublicRecordProductionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tv': typeof TvRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/downtime': typeof AuthenticatedDowntimeRoute
  '/_authenticated/super': typeof AuthenticatedSuperRoute
  '/api/public/admin-relay': typeof ApiPublicAdminRelayRoute
  '/api/public/record-production': typeof ApiPublicRecordProductionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv'
    | '/admin'
    | '/downtime'
    | '/super'
    | '/api/public/admin-relay'
    | '/api/public/record-production'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv'
    | '/admin'
    | '/downtime'
    | '/super'
    | '/api/public/admin-relay'
    | '/api/public/record-production'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tv'
    | '/_authenticated/admin'
    | '/_authenticated/downtime'
    | '/_authenticated/super'
    | '/api/public/admin-relay'
    | '/api/public/record-production'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TvRoute: typeof TvRoute
  ApiPublicAdminRelayRoute: typeof ApiPublicAdminRelayRoute
  ApiPublicRecordProductionRoute: typeof ApiPublicRecordProductionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downtime': {
      id: '/_authenticated/downtime'
      path: '/downtime'
      fullPath: '/downtime'
      preLoaderRoute: typeof AuthenticatedDowntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/record-production': {
      id: '/api/public/record-production'
      path: '/api/public/record-production'
      fullPath: '/api/public/record-production'
      preLoaderRoute: typeof ApiPublicRecordProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-relay': {
      id: '/api/public/admin-relay'
      path: '/api/public/admin-relay'
      fullPath: '/api/public/admin-relay'
      preLoaderRoute: typeof ApiPublicAdminRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDowntimeRoute: typeof AuthenticatedDowntimeRoute
  AuthenticatedSuperRoute: typeof AuthenticatedSuperRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDowntimeRoute: AuthenticatedDowntimeRoute,
  AuthenticatedSuperRoute: AuthenticatedSuperRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TvRoute: TvRoute,
  ApiPublicAdminRelayRoute: ApiPublicAdminRelayRoute,
  ApiPublicRecordProductionRoute: ApiPublicRecordProductionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
